version: '3'

services:
  db:
    image: node:16.14
    container_name: startingSequelize
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    depends_on:
      - database
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_HOST: database
      PORT: 3000

  database:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: mysqldb
    ports:
      - 5555:3306
    volumes:
      - ./:/docker-entrypoint-initdb.d
